import { NextRequest, NextResponse } from 'next/server';
import { getDb, COLLECTIONS } from '@/lib/mongodb';
import { getAuthUser } from '@/lib/auth-middleware';

export const dynamic = 'force-dynamic';

/**
 * GET /api/dashboard/stats
 * Returns real aggregate counts from MongoDB for the dashboard.
 */
export async function GET(req: NextRequest) {
  try {
    const user = getAuthUser(req);
    if (!user) return NextResponse.json({ error: 'Authentication required' }, { status: 401 });

    const db = await getDb();

    const [totalCourses, totalUsers, totalSyllabi, totalFeedback, totalPrograms] = await Promise.all([
      db.collection(COLLECTIONS.COURSES).countDocuments(),
      db.collection(COLLECTIONS.USERS).countDocuments(),
      db.collection(COLLECTIONS.SYLLABI).countDocuments(),
      db.collection(COLLECTIONS.FEEDBACK).countDocuments(),
      db.collection('programs').countDocuments(),
    ]);

    // Count by role
    const [students, faculty, admins] = await Promise.all([
      db.collection(COLLECTIONS.USERS).countDocuments({ role: 'STUDENT' }),
      db.collection(COLLECTIONS.USERS).countDocuments({ role: 'FACULTY' }),
      db.collection(COLLECTIONS.USERS).countDocuments({ role: 'ADMIN' }),
    ]);

    // Pending reviews
    const pendingReviews = await db.collection(COLLECTIONS.COURSES).countDocuments({ status: 'review' });

    // Courses with COs
    const coursesWithCOs = await db.collection(COLLECTIONS.COURSES).countDocuments({ cosCount: { $gt: 0 } });
    const completionRate = totalCourses > 0 ? Math.round((coursesWithCOs / totalCourses) * 100) : 0;

    return NextResponse.json({
      stats: {
        totalCourses,
        totalUsers,
        students,
        faculty,
        admins,
        totalSyllabi,
        totalFeedback,
        totalPrograms,
        pendingReviews,
        aiGenerated: totalSyllabi, // syllabi generated by AI
        completionRate,
      },
    });
  } catch (e) {
    console.error('[/api/dashboard/stats] Error:', e);
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}
